dist: xenial
language: python
python:
  - "3.8"
  
git:
  depth: false

# safelist
branches:
  only:
  - master
  - develop
  - /^\d+\.(?:\d+|x)(?:\.x)?$/

before_install:
  - nvm install 14
  - nvm use 14
  - pip install --upgrade pip setuptools jupyter_packaging jupyterlab wheel

install:
  - python setup.py sdist 

script:
  - black --check .

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: dist/sagemaker_run_notebook.0.22.0.tar.gz
  skip_cleanup: true
  on:
    tags: true